Delivery
MohammadMokhtarii/WebPush pull request #4
Opened 2024-03-11 13:59 UTC by Sobi1995

2024-03-11 14:18 UTC, behdadkd requested changes
❤️

2024-03-11 14:18 UTC, behdadkd commented on src/Directory.Packages.props
> +    <PackageVersion Include="RabbitMQ.Client" Version="6.6.0" />
use 6.8.1 veresion

2024-03-11 14:18 UTC, behdadkd commented on src/Services/Core/Core.Api/Core.Api.csproj
> +		<UserSecretsId>e4afb17d-f6a5-4142-a11c-96776823af2d</UserSecretsId>
remove user secret

2024-03-11 14:18 UTC, behdadkd commented on src/Services/Core/Core.Api/Dockerfile
> +#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.
merg main branch this is duplicate

2024-03-11 14:18 UTC, behdadkd commented on src/Services/Delivery/Delivery.csproj
> +    <UserSecretsId>dotnet-Delivery-da584e9e-1e55-4e03-8bf7-370f49f7f3f7</UserSecretsId>
remove user secret

2024-03-11 14:18 UTC, behdadkd commented on src/Services/Delivery/Dockerfile
> +FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
make it alpine

2024-03-11 14:18 UTC, behdadkd commented on src/Services/Delivery/Program.cs
> +
declare queue 
you can see example in behdadkd/DeleveryEngine Engine2

2024-03-11 14:18 UTC, behdadkd commented on src/Services/Delivery/Program.cs
> +    Console.WriteLine(message);
make a adaptor that make a 5 second task.delay and call it here insted of Console.WriteLine

2024-03-11 14:18 UTC, behdadkd commented on src/Services/Delivery/Worker.cs
> +namespace Delivery;
use a adapter and call it in +Recived on Cunsomer 
insted of this

2024-03-11 14:18 UTC, behdadkd commented on src/Services/Delivery/Program.cs
> +var factory = new ConnectionFactory { HostName = "rabbitmq", Port = 5672 };
use conection string from IConfiguration 
See "ProcessNotificationJob"

2024-03-11 14:18 UTC, behdadkd commented on src/docker-compose.override.yml
> +version: '3.4'
remove this file

2024-03-13 17:21 UTC, MohammadMokhtarii commented on .vscode/launch.json
.vscode folder must be ignored via .gitignore

2024-03-13 17:24 UTC, MohammadMokhtarii commented on src/Services/Core/Core.Api/Core.Api.csproj
> -		<DockerfileContext>..\..\..</DockerfileContext>
```
<DockerfileContext>..\..\..</DockerfileContext>
<DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
<InvariantGlobalization>false</InvariantGlobalization>
```

Shouldnt be Deleted For docker compose config in vs ide

2024-03-13 17:27 UTC, MohammadMokhtarii commented on src/Services/Delivery/Core/ProcessNotificationJob.cs
> +    private IModel _channel;
Channel Must be Declare For Every  AsyncEventingBasicConsumer InOrder to work properly if you are going to bind multiple consumer to queue

2024-03-13 17:27 UTC, MohammadMokhtarii commented on src/Services/Delivery/Core/ProcessNotificationJob.cs
> +        foreach (var number in Enumerable.Range(1, 10))
use fore instead of foreach

2024-03-13 17:30 UTC, MohammadMokhtarii commented on src/Services/Delivery/Delivery.csproj
> +  </PropertyGroup>
```
<PropertyGroup>
<TargetFramework>net8.0</TargetFramework>
<Nullable>enable</Nullable>
<ImplicitUsings>enable</ImplicitUsings>

</PropertyGroup>
```


Should be removed becasue it has been configed globally in directory.build.props

2024-03-13 17:32 UTC, MohammadMokhtarii commented on src/Services/Delivery/appsettings.json
> +  "ConnectionStrings": {
declare below config in  appsettings.Development.json

```
 "ConnectionStrings": {
    "MessageQueue": "amqp://guest:guest@rabbitmq:5672"
  },
```

2024-03-13 17:33 UTC, MohammadMokhtarii commented on src/docker-compose.yml
> +    image: ${DOCKER_REGISTRY-}dlselivery
dlselivery means?!

2024-03-16 10:58 UTC, MohammadMokhtarii approved these changes

2024-03-16 10:58 UTC, merged